#!/bin/bash

usage()
{
  echo "Usage: $0 [ -i IMAGE_ID ] [ -m MOUNT_DIRECTORY:WHERE_TO_MOUNT ]" 1>&2 
}
exit_abnormal()
{
  usage
  exit 1
}

HOST='iw276ws20-p10'
TAG='0.1'
DIRECTORY=''
options=':imh'
while getopts $options option
do
   case "${option}" in
   (h) usage
      exit 0
      ;;
   (i) HOST="${OPTARG}";;
   (m) DIRECTORY="-v ${OPTARG}";;
   (:) echo "Error: -${OPTARG} requires an argument."
      exit_abnormal
      ;;
   (*) exit_abnormal
      ;;
   esac
done

docker run -it --rm --runtime nvidia --network host ${DIRECTORY} ${HOST}:${TAG}
