# -*- coding: utf-8 -*-
"""PrepareDatasetDarknet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-TbXME89nLxACCQmnaSBQu2ha1ejXJGz
"""

workingDirectory = "/content"
outputDirectory = "/gdrive/My Drive/data"

"""Authenticate using your google drive!"""

from google.colab import drive
drive.mount('/gdrive')

"""## Download Dataset from bwsyncandshare and extract zips"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {workingDirectory}

!curl -L "https://bwsyncandshare.kit.edu/s/3nd3FKZPZXKNXPA/download" > dataset.zip; unzip dataset.zip; rm dataset.zip;

# Commented out IPython magic to ensure Python compatibility.
# %cd PANDA-Image
!unzip image_train_full.zip
!rm image_annos.zip
!rm image_train_full.zip
!rm image_test.zip
# %cd ..

"""## Set up convert & cropping scripts"""

# Commented out IPython magic to ensure Python compatibility.
!rm -r repo
!git clone https://github.com/IW276/IW276WS20-P10.git repo
# %cd repo/
!git checkout dev-marius
!pip install -r src/tools/requirements.txt
# %cd ..

"""## Run Scripts"""

import os
datasetDir = os.path.join(workingDirectory, "PANDA-Image")

!python repo/src/tools/generateImageCrops.py {datasetDir}

import os
splitJson = os.path.join(workingDirectory, "split/image_annos/split.json") 
cocoJson = os.path.join(workingDirectory, "coco.json")
imageTrainDir = os.path.join(workingDirectory, "split/image_train")
outTrainDir = os.path.join(workingDirectory, "out/train")

!python repo/src/tools/generateCocoJsonFile.py {splitJson} {cocoJson}

!python repo/src/tools/json2yolotxt.py annos {cocoJson} -darknet

!python repo/src/tools/splitInTrainAndValidate.py {imageTrainDir} {outTrainDir} 80 -darknet

"""## Copy files back to gdrive"""

import os
outImages = os.path.join(outputDirectory, "/images")
outLabels = os.path.join(outputDirectory, "/labels")
labels = os.path.join(workingDirectory, "out/train/labels")

trainTXT = os.path.join(workingDirectory, "out/train/train.txt")
valTXT = os.path.join(workingDirectory, "out/train/val.txt")
namesTXT = os.path.join(workingDirectory, "out/annos.names")

!mkdir {outImages}
!mkdir {outLabels}

# Commented out IPython magic to ensure Python compatibility.
# %cp {imageTrainDir}*.jpg {outImages}

# Commented out IPython magic to ensure Python compatibility.
# %cp {labels}*.txt {outLabels}

# Commented out IPython magic to ensure Python compatibility.
# %cp {trainTXT} {valTXT} {namesTXT} {outputDirectory}